    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import Crud.CrudProvedor;
import Formatos.Mensajes;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author james
 */
public class frmProvedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmProvedores
     */
    public frmProvedores() {
        initComponents();
        cargarDatosProveedores();
    }
    
   private void cargarDatosProveedores() {
    CrudProvedor conexionBD = new CrudProvedor();
    ResultSet datosProveedores = conexionBD.obtenerDatosProveedores(); // Obtiene todos los proveedores
    DefaultTableModel modeloTabla = (DefaultTableModel) tblPV.getModel();

    modeloTabla.setRowCount(0); // Limpiar la tabla antes de cargar nuevos datos

    try {
        while (datosProveedores.next()) {
            String ruc = datosProveedores.getString("NrRuc");
            String nombre = datosProveedores.getString("Nombre");
            String direccion = datosProveedores.getString("Direccion");
            String telefono = datosProveedores.getString("Telefono");

            modeloTabla.addRow(new Object[]{ruc, nombre, direccion, telefono});
        }
    } catch (SQLException ex) {
        Mensajes.M1("Error al cargar los datos de proveedores en la tabla: " + ex);
    }
}


/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnumPV = new javax.swing.JTextField();
        txtNomPV = new javax.swing.JTextField();
        txtDirecPV = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPV = new javax.swing.JTable();
        btnBuscarPV = new javax.swing.JButton();
        btnAgregarPV = new javax.swing.JButton();
        btnEliminarPV = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(53, 96, 154));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setText("Provedores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 320, 60));

        txtnumPV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° RUC", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
        txtnumPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumPVActionPerformed(evt);
            }
        });
        jPanel1.add(txtnumPV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 230, 70));

        txtNomPV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 3, 14))); // NOI18N
        jPanel1.add(txtNomPV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 230, 70));

        txtDirecPV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
        txtDirecPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirecPVActionPerformed(evt);
            }
        });
        jPanel1.add(txtDirecPV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 230, 70));

        tblPV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N°RUC", "Nombre", "Dirección", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPV);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 580, 420));

        btnBuscarPV.setText("Buscar");
        btnBuscarPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPVActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarPV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 140, 60));

        btnAgregarPV.setText("Agregar");
        btnAgregarPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPVActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarPV, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 140, 60));

        btnEliminarPV.setText("Eliminar");
        jPanel1.add(btnEliminarPV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumPVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumPVActionPerformed

    private void txtDirecPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirecPVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirecPVActionPerformed

    private void btnAgregarPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarPVActionPerformed


     

    private void btnBuscarPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPVActionPerformed
                                            
     // Paso 1: Obtener el NRUC ingresado en el campo de búsqueda.
    String Nruc = txtnumPV.getText();

    // Paso 2: Verificar si el campo de búsqueda no está vacío.
    if (!Nruc.isEmpty()) {
        // Paso 3: Realizar una consulta a la base de datos para obtener los datos del Prooverdor por nruc ingresado.
        CrudProvedor conexionBD = new CrudProvedor();
        ResultSet datosProveedor = conexionBD.obtenerDatosProveedorPorRUC(Nruc);

        DefaultTableModel modeloTabla = (DefaultTableModel) tblPV.getModel();

        // Paso 4: Limpiar la tabla antes de mostrar los nuevos datos.
        modeloTabla.setRowCount(0);

        try {
            boolean encontrado = false;

            // Paso 5: Llevar a cabo una búsqueda secuencial de los prooveedores en la base de datos.
            while (datosProveedor.next()) {
                // Paso 6: Obtener los datos del proovedor
                String NrRuc = datosProveedor.getString("NrRuc");
                String nombre = datosProveedor.getString("Nombre");
                String direccion = datosProveedor.getString("Direccion");
                String telefono = datosProveedor.getString("Telefono");

                // Paso 7: Agregar los datos del proovedor la tabla.
                modeloTabla.addRow(new Object[]{NrRuc, nombre, direccion, direccion, telefono});
                encontrado = true;
            }

            // Paso 8: Mostrar un mensaje si el proovedor no se encuentra.
            if (!encontrado) {
                Mensajes.M1("Proveedor no encontrado");
            }

            // Paso 9: Limpiar el campo de búsqueda después de mostrar los resultados.
            txtnumPV.setText("");
        } catch (SQLException ex) {
            // Paso 10: Manejar errores y mostrar un mensaje de error si ocurre una excepción.
            Mensajes.M1("Error al buscar al proveedor: " + ex);
        }
    }    
    }//GEN-LAST:event_btnBuscarPVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarPV;
    public javax.swing.JButton btnBuscarPV;
    public javax.swing.JButton btnEliminarPV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblPV;
    private javax.swing.JTextField txtDirecPV;
    private javax.swing.JTextField txtNomPV;
    public javax.swing.JTextField txtnumPV;
    // End of variables declaration//GEN-END:variables
}
